version: 2.1
jobs:
  build:
    working_directory: /code/Hessian-analysis-with-tf2_0/
    docker:
      - image: tensorflow/tensorflow:2.1.0-py3
    steps:
      - checkout
      - run:
          command: |
            pip install -r build-env/requirements.txt
      # - run:
      #     command: |
      #       python test/test_preprocess.py
      - run:
          command: |
            python test/test_eigens.py
      - run:
          command: |
            python test/test_hessians.py
      - run:
          command: |
            python test/test_grad_covariance.py