version: '2.3'
services:
  hessian-analysis-tf2_0:
    build: .
    volumes:
      - ~/Hessian-analysis-with-tf2_0/:/code/Hessian-analysis-with-tf2_0/
    # ports:
    #   - '1134:1134'
    #   comman: --port 1134
    runtime: nvidia